### ISSUE TITLE
Deprecation warnings

### ISSUE THREAD

**Issue by jugmac00** [zopefoundation/z3c.checkversions#14]
`tox -e=coverage` shows the following...

```
  Set up zope.testrunner.layer.UnitTests in 0.000 seconds.
/home/jugmac00/Projects/z3c.checkversions/.tox/coverage/lib/python3.7/site-packages/setuptools/depends.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
/home/jugmac00/Projects/z3c.checkversions/.tox/coverage/lib/python3.7/site-packages/zc/buildout/buildout.py:28: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import MutableMapping as DictMixin
/usr/lib/python3.7/doctest.py:2172: ResourceWarning: unclosed file <_io.BufferedWriter name=4>
  test.globs.clear()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/usr/lib/python3.7/doctest.py:2172: ResourceWarning: unclosed file <_io.BufferedReader name=5>
  test.globs.clear()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/usr/lib/python3.7/doctest.py:2172: ResourceWarning: unclosed file <_io.BufferedReader name=7>
  test.globs.clear()
```

**Comment by mgedmin** [comment]
> /home/jugmac00/Projects/z3c.checkversions/.tox/coverage/lib/python3.7/site-packages/setuptools/depends.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp

This is https://github.com/pypa/setuptools/issues/479

> /home/jugmac00/Projects/z3c.checkversions/.tox/coverage/lib/python3.7/site-packages/zc/buildout/buildout.py:28: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import MutableMapping as DictMixin

This is https://github.com/buildout/buildout/issues/484

> /usr/lib/python3.7/doctest.py:2172: ResourceWarning: unclosed file <_io.BufferedWriter name=4>
  test.globs.clear()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/usr/lib/python3.7/doctest.py:2172: ResourceWarning: unclosed file <_io.BufferedReader name=5>
  test.globs.clear()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/usr/lib/python3.7/doctest.py:2172: ResourceWarning: unclosed file <_io.BufferedReader name=7>
  test.globs.clear()

`PYTHONTRACEMALLOC=10 .tox/py38/bin/zope-testrunner --test-path=src` tells me this is the stdin, stdout and stderr attributes of the subprocess.Popen instance created in the 33rd example of buildout.txt.

Aside: I **hate** how doctest numbers examples instead of providing something useful like _line numbers_.  Oooof!

Anyway, this can fixed by https://github.com/zopefoundation/z3c.checkversions/pull/16

**Comment by jugmac00** [comment]
Currently, there are no more deprecation warnings :clap:
